apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
  labels:
    run: flask
spec:
  replicas: 2
  selector:
    matchLabels:
      run: flask
  template:
    metadata:
      name: flask
      labels:
        run: flask
    spec:
      containers:
        - name: flask
          image: mazenamria/server:v1.0
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: mongo.default.svc.cluster.local
            - name: DB_PORT
              value: '27001'
            - name: DB_NAME
              value: stats
            - name: DB_USER
              value: admin
            - name: DB_PASSWORD
              value: admin
            - name: HOST
              value: 192.168.204.169
            - name: HOST_USER
              value: root
            - name: HOST_PASSWORD
              value: root
