db_pv:
  capacity: 5Gi

flask:
  deployment:
    replicas: 2
    image: mazenamria/server:v1.0
  service:
    type: NodePort
    port: 5000
    targetPort: 5000

mongo:
  deployment:
    replicas: 1
  service:
    type: ClusterIP
    targetPort: 27017
    url: mongo.default.svc.cluster.local
