db_pv:
  capacity: 5Gi

api:
  deployment:
    replicas: 2
    image: mazenamria/api:v1.0
  service:
    type: NodePort
    port: 5000
    targetPort: 5000

collect:
  image: mazenamria/collect:v1.0
  schedule: "0 * * * *"

db:
  service:
    type: ClusterIP
    targetPort: 27017
    url: db.default.svc.cluster.local
