apiVersion: v1
kind: Service
metadata:
  name: flask
spec:
  type: {{ .Values.flask.service.type }}
  selector:
    run: flask
  ports:
    - port: {{ .Values.flask.service.port }}
      targetPort: {{ .Values.flask.service.targetPort }}
