apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
  labels:
    run: flask
spec:
  replicas: {{ .Values.flask.deployment.replicas }}
  selector:
    matchLabels:
      run: flask
  template:
    metadata:
      name: flask
      labels:
        run: flask
    spec:
      hostNetwork: true
      containers:
        - name: flask
          image: {{ .Values.flask.deployment.image  }}
          ports:
            - containerPort: {{ .Values.flask.service.port }}
          env:
            - name: DB_HOST
              value: mongo.default.svc.cluster.local
            - name: DB_PORT
              value: '27001'
            - name: DB_NAME
              value: stats
            - name: DB_USER
              value: admin
            - name: DB_PASSWORD
              value: admin
            - name: HOST
              value: 127.0.0.1
            - name: HOST_USER
              value: root
            - name: HOST_PASSWORD
              value: root
