apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  labels:
    run: mongo
spec:
  replicas: {{ .Values.mongo.deployment.replicas }}
  selector:
    matchLabels:
      run: mongo
  template:
    metadata:
      name: mongo
      labels:
        run: mongo
    spec:
      containers:
        - name: mongo
          image: bitnami/mongodb
          ports:
            - containerPort: 27001
          env:
            - name: MONGODB_USERNAME
              value: admin
            - name: MONGODB_PASSWORD
              value: admin
            - name: MONGODB_DATABASE
              value: stats
          volumeMounts:
            - name: db
              mountPath: /data/db
      volumes:
        - name: db
          persistentVolumeClaim:
            claimName: db
