apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  type: {{ .Values.api.service.type }}
  selector:
    run: api
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.targetPort }}
