apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  type: {{ .Values.db.service.type }}
  selector:
    run: db
  ports:
    - port: 27017
      targetPort: {{ .Values.db.service.targetPort }}
      name: db
