apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  type: {{ .Values.mongo.service.type }}
  selector:
    run: mongo
  ports:
    - port: 27017
      targetPort: {{ .Values.mongo.service.targetPort }}
      name: mongo
