apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  labels:
    run: mongo
spec:
  replicas: {{ .Values.mongo.deployment.replicas }}
  selector:
    matchLabels:
      run: mongo
  template:
    metadata:
      name: mongo
      labels:
        run: mongo
    spec:
      containers:
        - name: mongo
          image: bitnami/mongodb
          ports:
            - containerPort: 27017
          env:
            - name: MONGODB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: db
                  key: user
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db
                  key: password
            - name: MONGODB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: db
                  key: name
          volumeMounts:
            - name: db
              mountPath: /data/db
      volumes:
        - name: db
          persistentVolumeClaim:
            claimName: db
